// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerOrdersApp.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260506110257_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("dbo")
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("CustomerOrdersApp.Domain.Customers.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<int>("PublicId")
                    .HasColumnType("int");

                b.Property<int>("State")
                    .HasColumnType("int");

                b.Property<string>("Street")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ZipCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.HasKey("Id");

                b.HasIndex("PublicId")
                    .IsUnique();

                b.ToTable("Customers", "dbo");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Orders.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("datetime2");

                b.Property<int>("PublicId")
                    .HasColumnType("int");

                b.Property<DateTime>("RequiredDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ShippedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("PublicId")
                    .IsUnique();

                b.ToTable("CustomerOrders", "dbo");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Orders.OrderItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("Discount")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("FinalPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("ListPrice")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("OrderId")
                    .HasColumnType("int");

                b.Property<int>("PublicId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.HasIndex("PublicId")
                    .IsUnique();

                b.ToTable("OrderItems", "dbo");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Orders.Order", b =>
            {
                b.HasOne("CustomerOrdersApp.Domain.Customers.Customer", "Customer")
                    .WithMany("Orders")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Customer");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Orders.OrderItem", b =>
            {
                b.HasOne("CustomerOrdersApp.Domain.Orders.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Order");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Customers.Customer", b =>
            {
                b.Navigation("Orders");
            });

        modelBuilder.Entity("CustomerOrdersApp.Domain.Orders.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
